### ISSUE TITLE
Survival Analysis: Clinical Data table view is not within the bs Collapsbile frame

### ISSUE THREAD

**Issue by jasdumas** [jasdumas/shinyGEO#49]
![screen shot 2015-10-08 at 1 29 42 pm](https://cloud.githubusercontent.com/assets/6685750/10374603/ef583706-6dc1-11e5-8279-dd7d4254e592.jpeg)

**Comment by gdancik** [comment]
After looking at the newest version, I believe the reason I uncommented those originally was because then the columns were no longer lining up properly, at least in Safari. That is the case for the newest version, but it seems to work on Google Chrome. For now let's stick with Chrome and we'll have to add some javascript to the app to require that Google Chrome is used.
