### ISSUE TITLE
Code Generation

### ISSUE THREAD

**Issue by jasdumas** [jasdumas/shinyGEO#63]
Hi - I noticed that the ace editor code generation tab no longer shows code (I have been syncing my repo with yours now). It seems that from the last code organization you did, you moved all components for the _report_ and inadvertanly the reproducible code into the unused folder. The code and the comments is the file 'report.r' might say they are for the report but they were functionally correctly producing code in the editor and no longer into the report. My recommendation is to move lines 1 to 387 back into the server-output.r file.

I plan to work more on the code generation in the coming weeks and submit to **your** repo with any changes!

**Comment by gdancik** [comment]
Check out the latest version!

I added this code back in as well as made some edits since some of the code was not working correctly. The code works for the expression plot and the DE analysis (I didn't check for survival).
This is what still needs to be done: 
1. Don't repeat code (mainly the stripchart2 function) when adding code for the DE
2. When code is added, a modal should pop up informing the user of this (otherwise the user may not realize that code is added and may add code multiple times. We should prevent this latter case.
3. Code must be able to incorporate merging of columns or if user edits table and uploads. This can be handled by just setting the group values, for example, directly in the code (e.g., Y = c("M", "F", "M", "F", "M", etc), which is what GEO2R does.

I'll pick up with this over the weekend or early next week. If you can get anything done in the meantime, that would be great!

**Comment by jasdumas** [comment]
Awesome! I just updated my repo on the shinyapps version!
